### ISSUE TITLE
Singular name conflict with "addresses"

### ISSUE THREAD

**Issue by westito** [vattle/sqlboiler#94] opened 2017-01-21 11:35 UTC
### What version of SQLBoiler are you using (`sqlboiler --version`)?
SQLBoiler v2.1.7

### If this happened at runtime what code produced the issue? (if not applicable leave blank)
No, build time

### What is the output of the command above with the `-d` flag added to it? (Provided you are comfortable sharing this, it contains a blueprint of your schema)
its too large
"customers" have one address from "addresses" table

### Please provide a relevant database schema so we can replicate your issue (Provided you are comfortable sharing this)
i send it to email if request

### Further information. What did you do, what did you expect?
"addresses" table name in relationship loses its plurality when not need.
"addresses" -> "address" would be OK but maybe singular function runs twice on it:
> // AddAddresCustomers adds the given related objects to the existing relationships
>// of the address, optionally inserting them as new records.
>// Appends related to o.R.AddresCustomers.
>// Sets related.R.Addre appropriately.
And it causes bulding error
<img width="319" alt="screenshot 2017-01-21 12 19 52" src="https://cloud.githubusercontent.com/assets/536799/22174110/d5c95572-dfd5-11e6-8519-82716e2cce0d.png">

**Comment by westito** [comment] 2017-01-21 11:36
Here also missing an "s" letter
<img width="364" alt="screenshot 2017-01-21 12 36 31" src="https://cloud.githubusercontent.com/assets/536799/22174121/3f83a404-dfd6-11e6-8485-752a512287f4.png">

**Comment by westito** [comment] 2017-01-21 12:18
A found. I use foreign columns without pluralisation: "address_id", "customer_id" instead of "addresses_id", "customers_id". But I think the singular foreign key name is better because it's pointing to one object.
The solution:
<img width="675" alt="screenshot 2017-01-21 13 15 54" src="https://cloud.githubusercontent.com/assets/536799/22174326/00860552-dfdc-11e6-998e-693b639dd7a5.png">

And here is the patch:
```
diff --git a/boilingcore/text_helpers.go b/boilingcore/text_helpers.go
index 80506bd..8a9aa4e 100644
--- a/boilingcore/text_helpers.go
+++ b/boilingcore/text_helpers.go
@@ -196,7 +196,7 @@ func txtsFromToMany(tables []bdb.Table, table bdb.Table, rel bdb.ToManyRelations
 // fk == table = industry.Industry | industry.Industry
 // fk != table = industry.ParentIndustry | industry.Industry
 func txtNameToOne(fk bdb.ForeignKey) (localFn, foreignFn string) {
-	localFn = strmangle.Singular(trimSuffixes(fk.Column))
+	localFn = trimSuffixes(fk.Column)
 	fkeyIsTableName := localFn != strmangle.Singular(fk.ForeignTable)
 	localFn = strmangle.TitleCase(localFn)
 
@@ -235,8 +235,8 @@ func txtNameToOne(fk bdb.ForeignKey) (localFn, foreignFn string) {
 // fk != table = industry.MappedIndustryIndustry
 func txtNameToMany(toMany bdb.ToManyRelationship) (localFn, foreignFn string) {
 	if toMany.ToJoinTable {
-		localFkey := strmangle.Singular(trimSuffixes(toMany.JoinLocalColumn))
-		foreignFkey := strmangle.Singular(trimSuffixes(toMany.JoinForeignColumn))
+		localFkey := trimSuffixes(toMany.JoinLocalColumn)
+		foreignFkey := trimSuffixes(toMany.JoinForeignColumn)
 
 		if localFkey != strmangle.Singular(toMany.Table) {
 			foreignFn = strmangle.TitleCase(localFkey)
@@ -251,12 +251,12 @@ func txtNameToMany(toMany bdb.ToManyRelationship) (localFn, foreignFn string) {
 		return localFn, foreignFn
 	}
 
-	fkeyName := strmangle.Singular(trimSuffixes(toMany.ForeignColumn))
+	fkeyName := trimSuffixes(toMany.ForeignColumn)
 	if fkeyName != strmangle.Singular(toMany.Table) {
 		localFn = strmangle.TitleCase(fkeyName)
 	}
 	localFn += strmangle.TitleCase(strmangle.Plural(toMany.ForeignTable))
-	foreignFn = strmangle.TitleCase(strmangle.Singular(fkeyName))
+	foreignFn = strmangle.TitleCase(fkeyName)
 	return localFn, foreignFn
 }
```

**Comment by nullbio** [comment] 2017-01-24 02:59
Looking into this, however that patch isn't ideal because if we remove the Singular call the naming will be a bit funky for people who have oddly named columns (i.e. people using the plural forms instead of the singular forms like you are). The problem is in the ruleset for the inflection library.

**Comment by nullbio** [comment] 2017-01-24 03:33
Hi @westito, I think it's all fixed now. Can you please see if the dev branch works for you? I'd like to make sure before merging this into master, in case it created any new inflection problems. Thanks.

**Comment by bjyoungblood** [comment] 2017-01-24 17:23
I was seeing a similar issue (with a fk column was named `whitelabel_css_id`). The dev branch seems to have fixed it perfectly.

**Comment by aarondl** [comment] 2017-03-18 06:42
This issue is fixed and released.

**Closed by aarondl** 2017-03-18 06:42 UTC
